In [1]:
!pip install pylabwons

Collecting pylabwons
  Downloading pylabwons-1.3.8-py3-none-any.whl.metadata (466 bytes)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from pylabwons) (6.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pylabwons) (2.2.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from pylabwons) (5.24.1)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (from pylabwons) (18.1.0)
Collecting pykrx (from pylabwons)
  Downloading pykrx-1.2.8-py3-none-any.whl.metadata (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from pylabwons) (2025.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pylabwons) (1.16.3)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pylabwons) (0.14.6)
Collecting ta (from pylabwons)
  Downloading ta-0.11.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pylabwons) (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pylabwons) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pylabwons) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pylabwons) (2026.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->pylabwons) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly->pylabwons) (26.1)
Requirement already satisfied: requests>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from pykrx->pylabwons) (2.32.4)
Collecting deprecated>=1.2.14 (from pykrx->pylabwons)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: multipledispatch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pykrx->pylabwons) (1.0.0)
Requirement already satisfied: matplotlib>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from pykrx->pylabwons) (3.10.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pylabwons) (1.0.2)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated>=1.2.14->pykrx->pylabwons) (2.1.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8.0->pykrx->pylabwons) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pylabwons) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->pykrx->pylabwons) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->pykrx->pylabwons) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->pykrx->pylabwons) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->pykrx->pylabwons) (2026.4.22)
Downloading pylabwons-1.3.8-py3-none-any.whl (28 kB)
Downloading pykrx-1.2.8-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 32.7 MB/s eta 0:00:00a 0:00:01
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.11.0-py3-none-any.whl size=29412 sha256=bc21d7ee9215ae088328e2b1ae06f2bd8caf59e0c031bdec959c3bbedf650322
  Stored in directory: /root/.cache/pip/wheels/5c/a1/5f/c6b85a7d9452057be4ce68a8e45d77ba34234a6d46581777c6
Successfully built ta
Installing collected packages: deprecated, ta, pykrx, pylabwons
Successfully installed deprecated-1.3.1 pykrx-1.2.8 pylabwons-1.3.8 ta-0.11.0

# ASSET

| 구분 | XLE (대형주 중심) | XOP (탐사/생산 중심) | WTIU (3배 레버리지) |
| :--- | :--- | :--- | :--- |
| **기초 자산** | S&P 500 에너지 섹터 기업 | S&P Oil & Gas E&P 지수 | Solactive MicroSectors US Big Oil Index |
| **가중 방식** | **시가총액 가중** (대형주 비중↑) | **동일 가중** (모든 종목 균등 비중) | **동일 가중** (상위 12개 대형주 중심) |
| **운용 방식** | 1배수 (현물 ETF) | 1배수 (현물 ETF) | **일일 수익률 3배 추종 (ETN)** |
| **주요 종목** | 엑손모빌, 쉐브론 등 대기업 | 중소형 탐사·생산(E&P) 기업 | 엑손모빌, 쉐브론 등 우량주 12개 |
| **운용 보수** | **0.09%** | 0.35% | **0.95%** |
| **주요 특징** | 안정적인 대형주 및 배당 중심 | 유가 변동에 민감한 중소형주 포함 | 단기 방향성 매매용 (변동성 매우 높음) |

In [2]:
import yfinance as yf
import pandas as pd
import pandas_datareader.data as web
from datetime import datetime


# XOP: Energy Select Sector SPDR Fund
# XLE: SPDR S&P Oil & Gas Exploration & Production ETF
xop = yf.Ticker('XOP')
xle = yf.Ticker('XLE')
lev = yf.Ticker('WTIU')

objs = {}
for ticker in [xop, xle, lev]:
    ohlcv = ticker.history(period='10y', interval='1d')[['Open', 'High', 'Low', 'Close', 'Volume']]
    ohlcv.columns = ['open', 'high', 'low', 'close', 'volume']
    objs[ticker.ticker] = ohlcv
    

asset = pd.concat(objs, axis=1)
asset = asset.tz_localize(None) if asset.index.tz is not None else asset
# asset

# ANALYTICS

## 01. PE

In [5]:
print(f'XLE: \n  - TRAILING PE: {xle.info.get("trailingPE")}\n  - FORWARD PE: {xle.info.get("forwardPE")}')
print(f'XOP: \n  - TRAILING PE: {xop.info.get("trailingPE")}\n  - FORWARD PE: {xop.info.get("forwardPE")}')

XLE:
  - TRAILING PE: 20.7856
  - FORWARD PE: None
XOP:
  - TRAILING PE: 13.45099
  - FORWARD PE: -16866.0

## 02. ASSET-DXY

* DX-Y.NYB: US Dollar Index

In [6]:
dxy = yf.Ticker('DX-Y.NYB').history(period='10y', interval='1d')[['Open', 'High', 'Low', 'Close', 'Volume']]
dxy.columns = ['open', 'high', 'low', 'close', 'volume']
dxy = dxy.tz_localize(None) if dxy.index.tz is not None else dxy

### 02.01 Correlation

In [7]:
import pylabwons as lw

rel = lw.DualRelation(dxy['close'], asset['XLE']['close'], indicator_name='DXY', asset_name='XLE')
rel.corr

KRX 로그인 실패: KRX_ID 또는 KRX_PW 환경 변수가 설정되지 않았습니다.

,leading,leading_diff(d),lagging,lagging_diff(d),synchronous(ccf),cumulative(raw),synchronous(raw),relation
2025/11-2026/05,-0.140068,14,-0.173799,10,0.095676,0.620885,0.047233,low correlation
2025/08-2026/02,0.279666,19,0.212252,9,-0.078473,0.677676,-0.362363,19d leading
2025/05-2025/11,0.184078,19,0.171295,10,0.155829,0.709561,-0.293714,low correlation
2025/02-2025/08,0.255009,4,-0.199560,4,0.230826,0.735549,0.396133,4d leading
2024/11-2025/05,0.238495,4,-0.185804,4,0.142152,0.757258,0.555550,low correlation
2024/08-2025/02,-0.173198,8,-0.157710,19,0.075086,0.753082,0.259565,low correlation
2024/05-2024/11,0.126013,10,-0.205256,18,0.153528,0.731451,0.412861,low correlation
2024/02-2024/08,0.165148,1,-0.150103,14,-0.112294,0.730562,0.433836,low correlation
2023/11-2024/05,0.149782,6,0.169092,10,-0.292156,0.712832,0.530841,synchronous
2023/08-2024/02,0.163639,11,-0.297567,19,-0.117362,0.693182,0.434545,19d lagging
2023/05-2023/11,0.203494,11,-0.215935,19,-0.049808,0.677613,0.529333,low correlation
2023/02-2023/08,0.246948,14,-0.304125,11,-0.131650,0.640415,-0.192549,11d lagging
2022/11-2023/05,-0.243631,12,0.166669,14,-0.322960,0.621619,0.250103,synchronous
2022/08-2023/02,-0.237696,17,0.162811,14,-0.418229,0.591280,-0.468959,synchronous
2022/05-2022/11,0.189827,19,-0.200249,2,-0.356506,0.525088,0.007883,synchronous
2022/02-2022/08,-0.262746,7,0.246951,18,-0.162740,0.348579,0.241447,7d leading
2021/11-2022/05,-0.166755,7,-0.182655,20,0.054397,0.158854,0.753338,low correlation
2021/08-2022/02,0.141201,17,0.145825,5,-0.150779,0.061767,0.711938,low correlation
2021/05-2021/11,0.213665,10,0.238445,3,-0.349253,0.057133,0.116794,synchronous
2021/02-2021/08,0.144670,14,-0.227548,17,-0.245360,0.055809,-0.077730,low correlation
2020/11-2021/05,0.170860,14,-0.175699,7,-0.084846,0.063717,-0.000464,low correlation
2020/08-2021/02,-0.163510,16,0.270808,17,-0.094929,0.036337,-0.831128,17d lagging
2020/05-2020/11,-0.261118,1,-0.194577,13,-0.236309,-0.101031,0.494781,1d leading
2020/02-2020/08,-0.470851,1,0.264085,5,-0.023235,-0.295305,-0.213650,1d leading
2019/11-2020/05,-0.496504,1,0.317070,5,0.079045,-0.312489,-0.655518,1d leading
2019/07-2020/01,0.186644,7,-0.245831,1,0.276752,-0.195170,-0.400740,synchronous
2019/04-2019/10,0.270966,7,-0.198679,1,0.070793,-0.169590,-0.477677,7d leading
2019/01-2019/07,-0.138506,15,-0.227813,1,-0.158077,-0.099992,-0.179847,low correlation
2018/10-2019/04,0.215595,8,0.241084,11,-0.073909,-0.072333,0.290159,low correlation
2018/07-2019/01,-0.189449,1,-0.299385,18,-0.068776,-0.071175,-0.672087,18d lagging
2018/04-2018/10,-0.206005,1,-0.162155,3,-0.097496,-0.050918,-0.419140,low correlation
2018/01-2018/07,-0.142765,11,0.191475,9,-0.246925,-0.043088,0.821171,low correlation
2017/10-2018/04,-0.151147,14,0.232523,9,-0.224302,0.065889,-0.180283,low correlation
2017/07-2018/01,-0.192284,1,0.178787,3,0.041380,0.228339,-0.491761,low correlation
2017/04-2017/10,0.241373,20,0.164181,20,0.178867,0.725550,0.011846,low correlation
2017/01-2017/07,-0.223836,8,-0.282504,18,0.075991,0.798627,0.818813,18d lagging
2016/10-2017/04,0.224710,10,0.203656,11,0.073205,0.818113,0.708523,low correlation
2016/07-2017/01,0.261418,6,0.152746,8,-0.069115,0.870157,0.863184,6d leading

### 02.02. Plot

In [8]:
import plotly.io as pio
pio.renderers.default = "vscode"

fig = rel.plotly()
fig.update_layout(height=600)

## 03. ASSET-FUTURES

* CL=F: WTI Crude Oil Futures
* BZ=F: Brent Crude Oil Futures
* NG=F: Natural Gas Futures

| 구분 | WTI (서부 텍사스산) | Brent (브렌트유) | Dubai (두바이유) |
| :--- | :--- | :--- | :--- |
| **TICKER** | CL=F | BZ=F | None |
| **기준 지역** | 미국 내륙 (텍사스 중심) | 유럽 북해 (해상) | 중동 (아랍에미리트) |
| **품질** | **최상** (가장 가벼운 경질유) | **우수** (고품질 경질유) | **보통** (황 함량 높은 중질유) |
| **운송 방식** | 파이프라인 (내륙 운송) | 유조선 (해상 운송 유리) | 유조선 (해상 운송 중심) |
| **주요 시장** | 미국 내 유가 지표 | **전 세계 유가 기준 (2/3)** | 아시아 시장 가격 기준 |
| **거래소** | NYMEX (뉴욕상업거래소) | ICE (런던선물거래소) | 현물 거래 중심 |

In [9]:
cl_f = yf.Ticker('CL=F')
bz_f = yf.Ticker('BZ=F')
ng_f = yf.Ticker('NG=F')
objs = {}
for ticker in [cl_f, bz_f, ng_f]:
    ohlcv = ticker.history(period='10y', interval='1d')[['Open', 'High', 'Low', 'Close', 'Volume']]
    ohlcv.columns = ['open', 'high', 'low', 'close', 'volume']
    objs[ticker.ticker] = ohlcv
futures = pd.concat(objs, axis=1)
futures = futures.tz_localize(None) if futures.index.tz is not None else futures

### 03.01. Correlation

In [10]:
sym = 'CL=F'
rel = lw.DualRelation(futures[sym]['close'], asset['XOP']['close'], indicator_name=sym, asset_name='XOP')
rel.corr

/usr/local/lib/python3.12/dist-packages/pandas/core/internals/blocks.py:393: RuntimeWarning:

invalid value encountered in log

,leading,leading_diff(d),lagging,lagging_diff(d),synchronous(ccf),cumulative(raw),synchronous(raw),relation
2025/11-2026/05,0.195791,20,0.253784,20,0.627152,0.578898,0.954035,synchronous
2025/08-2026/02,-0.246710,9,-0.178079,9,0.678805,0.549661,0.388747,synchronous
2025/05-2025/11,-0.219819,9,-0.186688,3,0.617500,0.560388,0.306682,synchronous
2025/02-2025/08,-0.258146,19,-0.147930,9,0.685084,0.566926,0.821818,synchronous
2024/11-2025/05,-0.256242,14,0.180740,20,0.714495,0.568273,0.826393,synchronous
2024/08-2025/02,-0.222178,7,-0.237574,18,0.538152,0.568110,0.381448,synchronous
2024/05-2024/11,0.163480,12,0.157392,1,0.584816,0.566342,0.826544,synchronous
2024/02-2024/08,0.191673,1,0.331594,9,0.496469,0.562962,0.699791,synchronous
2023/11-2024/05,-0.243143,8,0.145381,18,0.558902,0.551282,0.886400,synchronous
2023/08-2024/02,-0.194144,3,-0.176608,10,0.628349,0.534678,0.840830,synchronous
2023/05-2023/11,0.169416,7,-0.168151,5,0.634632,0.527859,0.908906,synchronous
2023/02-2023/08,0.234324,18,-0.130826,19,0.661929,0.502811,0.819658,synchronous
2022/11-2023/05,0.221614,1,-0.112684,3,0.641949,0.495192,0.808853,synchronous
2022/08-2023/02,0.187050,1,-0.188233,5,0.660085,0.485259,0.338183,synchronous
2022/05-2022/11,-0.189950,10,-0.200398,18,0.646354,0.464657,0.193888,synchronous
2022/02-2022/08,0.157947,12,-0.185892,18,0.558638,0.434343,0.710018,synchronous
2021/11-2022/05,-0.149208,10,0.215398,11,0.573691,0.409826,0.872021,synchronous
2021/08-2022/02,-0.221011,18,0.220364,11,0.679328,0.421686,0.874415,synchronous
2021/05-2021/11,0.204875,1,0.248083,20,0.683862,0.464305,0.856462,synchronous
2021/02-2021/08,-0.233770,16,-0.238278,18,0.654627,0.532477,0.786986,synchronous
2020/11-2021/05,-0.140747,15,0.188544,4,0.629263,0.606521,0.974587,synchronous
2020/08-2021/02,-0.156981,15,-0.162594,6,0.567566,0.659406,0.949500,synchronous
2020/05-2020/11,-0.172745,12,0.180209,11,0.378697,0.664784,0.005465,synchronous
2020/02-2020/08,0.453878,7,0.189123,3,0.469735,0.632937,0.685974,synchronous
2019/11-2020/05,0.534053,7,0.181189,3,0.503601,0.556741,0.885530,7d leading
2019/07-2020/01,-0.170049,10,0.141299,18,0.703351,0.297063,0.677086,synchronous
2019/04-2019/10,-0.227146,2,-0.148439,17,0.725668,0.377822,0.756152,synchronous
2019/01-2019/07,-0.215291,18,0.127015,9,0.637354,0.457648,0.595483,synchronous
2018/10-2019/04,0.233010,2,-0.204441,11,0.636243,0.572098,0.624261,synchronous
2018/07-2019/01,-0.188483,11,0.217369,4,0.676295,0.664147,0.969156,synchronous
2018/04-2018/10,-0.228668,10,0.174103,4,0.654901,0.674456,0.570917,synchronous
2018/01-2018/07,-0.152409,12,-0.158666,12,0.665837,0.589800,0.863777,synchronous
2017/10-2018/04,-0.147156,17,-0.127637,2,0.665593,0.318756,0.503431,synchronous
2017/07-2018/01,0.204186,15,-0.140035,11,0.600783,0.445258,0.949814,synchronous
2017/04-2017/10,0.186625,15,0.158168,5,0.676711,0.510438,0.459708,synchronous
2017/01-2017/07,-0.200493,17,-0.183795,7,0.682593,0.689414,0.897681,synchronous
2016/10-2017/04,0.205558,6,-0.180730,12,0.658031,0.687156,0.569022,synchronous
2016/07-2017/01,0.139958,6,-0.251269,20,0.749353,0.743876,0.875123,synchronous

### 03.02. Plot

In [11]:
fig = rel.plotly()
fig.update_layout(height=600)

## 04. ASSET-OIL PRICE

* DCOILBRENTEU: Crude Oil Prices: Brent - Europe
* DCOILWTICO: Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma

In [12]:
today = datetime.now()
start = datetime(today.year - 10, today.month, today.day)
others = web.DataReader(['DCOILBRENTEU', 'DCOILWTICO'], 'fred', start, today)

### 04.01. Correlation

In [14]:
sym = 'DCOILWTICO'
rel = lw.DualRelation(others['DCOILWTICO'], asset['XLE']['close'], indicator_name=sym, asset_name='XLE')
rel.corr

/usr/local/lib/python3.12/dist-packages/pandas/core/internals/blocks.py:393: RuntimeWarning:

invalid value encountered in log

,leading,leading_diff(d),lagging,lagging_diff(d),synchronous(ccf),cumulative(raw),synchronous(raw),relation
2025/11-2026/05,0.265758,4,-0.170636,19,0.517365,0.646839,0.874122,synchronous
2025/08-2026/02,0.201932,17,0.139548,7,0.634150,0.632932,-0.148316,synchronous
2025/05-2025/11,0.207847,1,-0.157508,3,0.570640,0.672922,0.152632,synchronous
2025/02-2025/08,-0.265833,9,-0.172812,9,0.671493,0.700022,0.842919,synchronous
2024/11-2025/05,-0.321417,14,-0.158201,3,0.678817,0.716604,0.604727,synchronous
2024/07-2025/01,-0.175017,16,-0.196060,7,0.525712,0.735501,0.096267,synchronous
2024/04-2024/10,0.154402,12,-0.157138,5,0.598398,0.751760,0.508962,synchronous
2024/01-2024/07,0.184967,15,0.236615,9,0.472651,0.766323,0.722658,synchronous
2023/10-2024/04,-0.205853,8,0.178772,18,0.545949,0.768959,0.865676,synchronous
2023/07-2024/01,-0.211977,9,-0.199077,13,0.631315,0.769867,0.872636,synchronous
2023/04-2023/10,0.211106,7,0.166923,16,0.667675,0.778827,0.956840,synchronous
2023/01-2023/07,0.217764,18,-0.181044,19,0.679920,0.771525,0.895879,synchronous
2022/10-2023/04,0.215931,1,-0.186424,13,0.596339,0.785184,0.792847,synchronous
2022/07-2023/01,-0.130389,9,0.177709,17,0.668824,0.801925,-0.403138,synchronous
2022/04-2022/10,0.205927,15,-0.229093,20,0.679895,0.833451,0.175901,synchronous
2022/01-2022/07,0.145159,12,-0.156359,18,0.590232,0.820929,0.796683,synchronous
2021/10-2022/04,0.184866,16,-0.175120,5,0.650907,0.759641,0.928596,synchronous
2021/07-2022/01,0.185857,1,0.209085,8,0.722393,0.679863,0.833724,synchronous
2021/04-2021/10,0.187725,20,0.255010,20,0.697958,0.674988,0.711969,synchronous
2021/01-2021/07,-0.213478,16,-0.293265,18,0.641819,0.720905,0.813988,synchronous
2020/10-2021/04,0.153953,1,-0.299239,18,0.593730,0.757365,0.966602,synchronous
2020/07-2021/01,0.152248,7,-0.194660,1,0.569079,0.791906,0.898325,synchronous
2020/04-2020/10,0.116865,1,0.223976,12,0.291820,0.805681,-0.112295,synchronous
2020/01-2020/07,0.298153,7,0.238848,3,0.327994,0.826518,0.752545,synchronous
2019/10-2020/04,0.321741,7,0.231546,3,0.327986,0.802396,0.911432,synchronous
2019/07-2020/01,-0.183703,10,0.170318,7,0.558490,0.691485,0.805382,synchronous
2019/04-2019/10,-0.272176,18,-0.163894,17,0.630703,0.728307,0.742692,synchronous
2019/01-2019/07,-0.283852,18,-0.208629,6,0.665021,0.782000,0.693632,synchronous
2018/10-2019/04,-0.181198,13,0.170464,8,0.574337,0.817218,0.864636,synchronous
2018/07-2019/01,-0.197399,18,-0.162556,12,0.592239,0.827011,0.948312,synchronous
2018/04-2018/10,-0.172773,10,-0.216916,12,0.610322,0.841080,0.484737,synchronous
2018/01-2018/07,-0.159264,8,0.194944,11,0.598275,0.798094,0.808158,synchronous
2017/10-2018/04,0.133621,5,-0.155181,9,0.601448,0.648878,0.523246,synchronous
2017/07-2018/01,0.165316,15,-0.172396,11,0.519516,0.728500,0.927665,synchronous
2017/04-2017/10,0.293266,15,-0.220639,7,0.654904,0.643131,0.670469,synchronous
2017/01-2017/07,0.205761,20,-0.221336,7,0.640916,0.703156,0.873421,synchronous
2016/10-2017/04,-0.193719,15,-0.144546,11,0.644145,0.685115,0.599046,synchronous
2016/07-2017/01,-0.205271,2,-0.203552,18,0.707632,0.681249,0.872683,synchronous

### 04.02. Plot

In [15]:
fig = rel.plotly()
fig.update_layout(height=600)

## 05. ASSET-PPI

* PCU213111213111: Producer Price Index by Industry: Drilling Oil and Gas Wells

In [16]:
today = datetime.now()
start = datetime(today.year - 10, today.month, today.day)
others = web.DataReader(['PCU213111213111'], 'fred', start, today)

### 05.01. Correlation

In [17]:
rel = lw.DualRelation(others['PCU213111213111'].dropna(), asset['XLE']['close'], asset_name='XLE', window=24, max_lag=6)
rel.corr

,leading,leading_diff(m),lagging,lagging_diff(m),synchronous(ccf),cumulative(raw),synchronous(raw),relation
2024/03-2026/03,0.393463,2,-0.250569,1,0.030782,0.930909,-0.462023,2m leading
2023/03-2025/03,0.411513,1,-0.289753,3,0.419991,0.939259,0.452758,synchronous
2022/03-2024/03,-0.559929,2,-0.323810,4,0.180465,0.918422,0.801696,2m leading
2021/03-2023/03,-0.327376,4,-0.416250,6,-0.030197,0.858749,0.950162,6m lagging
2020/03-2022/03,0.258619,3,0.232956,1,0.153167,0.580092,0.831943,3m leading
2019/03-2021/03,0.324156,1,0.274025,5,0.174528,0.513241,0.880947,1m leading
2018/03-2020/03,0.380227,6,0.464641,4,0.067987,0.000072,0.181003,4m lagging
2017/03-2019/03,0.216814,6,-0.302136,1,-0.086932,0.130482,0.035914,1m lagging

### 05.02. Plot

In [18]:
fig = rel.plotly()
fig.update_layout(height=600)

## 06. ASSET-TREASURY

In [19]:
today = datetime.now()
start = datetime(today.year - 10, today.month, today.day)
others = web.DataReader(['DGS10', 'T10Y2Y', 'BAMLH0A0HYM2'], 'fred', start, today)

### 06.01. Correlation

In [20]:
rel = lw.DualRelation(others['BAMLH0A0HYM2'].dropna(), asset['XLE']['close'], asset_name='XLE')
rel.corr

,leading,leading_diff(d),lagging,lagging_diff(d),synchronous(ccf),cumulative(raw),synchronous(raw),relation
2025/11-2026/05,-0.174953,14,-0.189828,14,0.149132,-0.520040,0.329055,low correlation
2025/08-2026/02,0.323962,11,-0.160360,12,-0.198652,-0.744223,-0.350647,11d leading
2025/05-2025/11,-0.179768,14,-0.233204,3,-0.330395,-0.757562,-0.792811,synchronous
2025/02-2025/08,0.254623,19,-0.216806,20,-0.577842,-0.745268,-0.678094,synchronous
2024/11-2025/05,0.256951,14,-0.220166,20,-0.583641,-0.756974,-0.709330,synchronous
2024/08-2025/02,-0.209408,1,0.274178,18,-0.327294,-0.756499,-0.570403,synchronous
2024/05-2024/11,-0.153916,8,-0.202225,1,-0.397051,-0.738573,-0.529175,synchronous
2024/02-2024/08,-0.253925,1,-0.173388,1,-0.329775,-0.715979,-0.484600,synchronous
2023/11-2024/05,-0.251323,18,0.200426,15,-0.232032,-0.625641,-0.697939,18d leading
2023/08-2024/02,-0.256952,18,0.192596,16,-0.230110,-0.327975,0.377347,18d leading

### 06.02. Plot

In [21]:
fig = rel.plotly()
fig.update_layout(height=600)